/**
 * mantraData.ts
 *
 * All preset mantras with their normalized forms, aliases,
 * and matching configuration.
 *
 * Each MantraConfig includes both Hindi/Devanagari and
 * romanized forms so the engine can match chanting in
 * either script.
 */

import { MantraConfig } from '@/types/mantra';

export const PRESET_MANTRAS: MantraConfig[] = [
  // ─────────────────── Divine Names ──────────────────────────
  {
    id: 'ram',
    displayName: 'श्री राम',
    originalScript: 'राम',
    language: 'hi-IN',
    normalizedForms: ['राम', 'ram', 'raam', 'rama', 'shri ram', 'श्री राम'],
    aliases: ['raam', 'rama', 'shri ram', 'jai ram'],
    minimumSimilarity: 0.72,
    duplicateWindowMs: 1200,
    description: 'Lord Ram — the ideal king and seventh avatar of Vishnu',
    deity: 'Vishnu',
    meaning: {
      shortMeaning: 'Ra = radiance of Brahman, Ma = in me — "The Divine Light is within me"',
      fullMeaning: '"Ram" is a taraka mantra — a mantra that takes us across the ocean of samsara. It contains the life-force (prana) of all 1008 names of Vishnu and 1008 names of Shiva.',
      mahatmya: 'Goswami Tulsidas says "Ram naam" equals all the Vedas. Lord Shiva himself chants Ram Naam as the greatest mantra.',
      source: 'Ramcharitmanas, Skanda Purana',
    },
    bestTime: 'Brahma Muhurta (4-6am), any time',
    recommendedFor: 'Liberation, Peace, All-round wellbeing',
  },
  {
    id: 'krishna',
    displayName: 'श्री कृष्ण',
    originalScript: 'कृष्ण',
    language: 'hi-IN',
    normalizedForms: ['कृष्ण', 'krishna', 'krishn', 'krushna'],
    aliases: ['kanha', 'kanhaiya', 'shri krishna', 'gopal', 'govind'],
    minimumSimilarity: 0.72,
    duplicateWindowMs: 1200,
    description: 'Lord Krishna — the divine statesman, eighth avatar of Vishnu',
    deity: 'Vishnu',
    meaning: {
      shortMeaning: 'Krishn = one who attracts all — "The all-attracting Supreme"',
      mahatmya: 'Bhagwad Gita mein Shri Krishna ne kaha — "Nitya mera naam jap"',
      source: 'Bhagwad Gita, Srimad Bhagavatam',
    },
    bestTime: 'Brahma Muhurta, Shukravar',
    recommendedFor: 'Bhakti, Anand, Moksha',
  },
  {
    id: 'radha',
    displayName: 'राधा',
    originalScript: 'राधा',
    language: 'hi-IN',
    normalizedForms: ['राधा', 'radha', 'raadha'],
    aliases: ['radhe', 'radhey', 'shri radha'],
    minimumSimilarity: 0.72,
    duplicateWindowMs: 1200,
    description: 'Radha — embodiment of divine love and devotion',
    deity: 'Radha',
    meaning: {
      shortMeaning: 'Radha = "worshipped" — the divine Shakti of Krishna',
      mahatmya: '"Radha" naam mein "Ra" Prakriti hai aur "Dha" Purusha — dono ka milan',
      source: 'Brahma Vaivarta Purana',
    },
    bestTime: 'Sandhya, Shukravar',
    recommendedFor: 'Prem, Bhakti, Anand',
  },
  {
    id: 'shiv',
    displayName: 'शिव',
    originalScript: 'शिव',
    language: 'hi-IN',
    normalizedForms: ['शिव', 'shiv', 'shiva', 'siva'],
    aliases: ['shiv', 'shankar', 'mahadev', 'bholenath', 'har'],
    minimumSimilarity: 0.72,
    duplicateWindowMs: 1200,
    description: 'Lord Shiva — the destroyer and transformer',
    deity: 'Shiva',
    meaning: {
      shortMeaning: 'Shiv = "auspicious, the good one" — Param Kalyan ka swaroop',
      mahatmya: 'Shiv naam mein sare paapon ka naash hota hai. Somvar ke din Shiv jap vishesh phal deta hai.',
      source: 'Shiva Purana, Mahabharat',
    },
    bestTime: 'Somvar (Monday), Pradosh',
    recommendedFor: 'Moksha, Aanand, Nirbhayata',
  },
  {
    id: 'hanuman',
    displayName: 'हनुमान',
    originalScript: 'हनुमान',
    language: 'hi-IN',
    normalizedForms: ['हनुमान', 'hanuman', 'hanumanji'],
    aliases: ['bajrangbali', 'maruti', 'anjaneya', 'pawan putra'],
    minimumSimilarity: 0.72,
    duplicateWindowMs: 1200,
    description: 'Lord Hanuman — the devoted servant of Ram',
    deity: 'Hanuman',
    meaning: {
      shortMeaning: 'Hanuman = "broken-jawed one" — vinaash hone ke baad bhi sthir rahne wala',
      mahatmya: 'Hanuman naam ke jap se bhoot-baadha, rog aur bhay door hote hain. Mangalvar ko 108 baar jap karna shreshtha hai.',
      source: 'Valmiki Ramayan, Hanuman Chalisa',
    },
    bestTime: 'Brahma Muhurta, Mangalvar (Tuesday)',
    recommendedFor: 'Shakti, Raksha, Bhay-mukti',
  },
  {
    id: 'ganesh',
    displayName: 'गणेश',
    originalScript: 'गणेश',
    language: 'hi-IN',
    normalizedForms: ['गणेश', 'ganesh', 'ganesh ji', 'ganesha'],
    aliases: ['ganapati', 'vinayak', 'vighnesh', 'lambodar'],
    minimumSimilarity: 0.72,
    duplicateWindowMs: 1200,
    description: 'Lord Ganesha — remover of obstacles',
    deity: 'Ganesha',
    meaning: {
      shortMeaning: 'Ganesha = "Gana + Isha" — ganon ka swami, parivaar ka palan karne wala',
      mahatmya: 'Har karya se pehle Ganesh jap se safalta milti hai. Chaturthi tithi ko 108 jap vishesh',
      source: 'Ganesh Purana, Mudgala Purana',
    },
    bestTime: 'Budhvar (Wednesday), Chaturthi Tithi',
    recommendedFor: 'Vighn-naash, Safalta, Vidya',
  },
  {
    id: 'durga',
    displayName: 'दुर्गा',
    originalScript: 'दुर्गा',
    language: 'hi-IN',
    normalizedForms: ['दुर्गा', 'durga', 'maa durga'],
    aliases: ['ambika', 'chamunda', 'bhavani', 'sheranwali', 'amba'],
    minimumSimilarity: 0.72,
    duplicateWindowMs: 1200,
    description: 'Goddess Durga — the divine mother and slayer of evil',
    deity: 'Shakti',
    meaning: {
      shortMeaning: 'Durga = "dur" (difficult) + "ga" (to cross) — jo durgam paristhitiyon ko par karwa de',
      mahatmya: 'Navratri mein Durga jap se sare paap nasht hote hain aur Shakti ki prapti hoti hai.',
      source: 'Devi Mahatmya (Durga Saptashati), Markandeya Purana',
    },
    bestTime: 'Navratri, Shukravar',
    recommendedFor: 'Shakti, Suraksha, Vigyan-mukti',
  },
  {
    id: 'sita',
    displayName: 'सीता',
    originalScript: 'सीता',
    language: 'hi-IN',
    normalizedForms: ['सीता', 'sita', 'seeta', 'sitaji'],
    aliases: ['janaki', 'vaidehi', 'maithili'],
    minimumSimilarity: 0.72,
    duplicateWindowMs: 1200,
    description: 'Goddess Sita — embodiment of purity and devotion',
    deity: 'Sita',
    meaning: {
      shortMeaning: 'Sita = "furrow" — bhumi se utpanna, parishuddha prakriti ki pratik',
      mahatmya: '"Sita Ram" jap karne se grihastha mein sukh aur prem ki prapti hoti hai.',
      source: 'Valmiki Ramayan',
    },
    bestTime: 'Brahma Muhurta, Guruvar',
    recommendedFor: 'Pativratta shakti, Grihasthi sukh, Pavitrata',
  },
  {
    id: 'lakshmi',
    displayName: 'लक्ष्मी',
    originalScript: 'लक्ष्मी',
    language: 'hi-IN',
    normalizedForms: ['लक्ष्मी', 'lakshmi', 'laxmi', 'lakshmi ji'],
    aliases: ['mahalakshmi', 'kamala', 'padma'],
    minimumSimilarity: 0.72,
    duplicateWindowMs: 1200,
    description: 'Goddess Lakshmi — goddess of wealth and prosperity',
    deity: 'Shakti',
    meaning: {
      shortMeaning: 'Lakshmi = "laksha" (aim/sign) — jo shubh sanket deti hai',
      mahatmya: 'Shukravar ko 108 baar Lakshmi naam jap karne se grih mein samriddhi aati hai.',
      source: 'Shri Sukta, Vishnu Purana',
    },
    bestTime: 'Shukravar (Friday), Diwali',
    recommendedFor: 'Samriddhi, Aishwarya, Griha sukh',
  },
  {
    id: 'narayan',
    displayName: 'नारायण',
    originalScript: 'नारायण',
    language: 'hi-IN',
    normalizedForms: ['नारायण', 'narayan', 'narayana', 'narayan ji'],
    aliases: ['hari', 'vishnu', 'om namo narayana'],
    minimumSimilarity: 0.72,
    duplicateWindowMs: 1200,
    description: 'Narayan — the sustainer, another name for Vishnu',
    deity: 'Vishnu',
    meaning: {
      shortMeaning: 'Narayan = "nara" (jeev) + "ayana" (aashray) — jeevaatma ka param aashray',
      mahatmya: '"Narayan" naam ke jap se Vishnu ka aashirvaad milta hai aur parishram ka phal teen guna hota hai.',
      source: 'Srimad Bhagavatam, Vishnu Purana',
    },
    bestTime: 'Guruvar (Thursday), Ekadashi',
    recommendedFor: 'Moksha, Raksha, Sampoorna kalyan',
  },
  // ─────────────────── Mantras ───────────────────────────────
  {
    id: 'om-namah-shivaya',
    displayName: 'ॐ नमः शिवाय',
    originalScript: 'ॐ नमः शिवाय',
    language: 'hi-IN',
    normalizedForms: [
      'ॐ नमः शिवाय',
      'om namah shivaya',
      'om namah sivaya',
    ],
    aliases: ['namah shivaya', 'om namo shivaya', 'om namah shiva'],
    minimumSimilarity: 0.68,
    duplicateWindowMs: 2000,
    description: 'The Panchakshara mantra of Lord Shiva',
    deity: 'Shiva',
    meaning: {
      shortMeaning: '"Na Ma Shi Va Ya" — panch tattva (prithvi, jal, agni, vayu, aakash) ka prateek',
      fullMeaning: 'Panchakshara mantra — "Om" Brahman hai, "Namah" shuddh samarpan hai, "Shivaya" Shiv ko — "Main Shiv ke charan mein samarpan hoon"',
      mahatmya: 'Shiva Purana ke anusaar is mantra ka jaap 1 crore baar karne se Shiv saakshat milte hain.',
      source: 'Shiva Purana, Krishna Yajurveda',
    },
    bestTime: 'Somvar, Shivratri, Pradosh',
    recommendedFor: 'Moksha, Aanand, Dukha-naash',
  },
  {
    id: 'shri-ram-jai-ram',
    displayName: 'श्री राम जय राम',
    originalScript: 'श्री राम जय राम जय जय राम',
    language: 'hi-IN',
    normalizedForms: [
      'श्री राम जय राम जय जय राम',
      'shri ram jai ram jai jai ram',
      'shri ram jay ram jay jay ram',
    ],
    aliases: [
      'jai ram',
      'jay ram',
      'shri ram jai ram',
      'shri ram jay ram',
    ],
    minimumSimilarity: 0.65,
    duplicateWindowMs: 3000,
    description: 'Victory to Sri Ram — chanted by Tukaram and in Warkari tradition',
    deity: 'Vishnu',
    meaning: {
      shortMeaning: '"Jai" = jaya, vijay — Shri Ram ki vijay ka udghoshan',
      mahatmya: 'Warkari sampraday mein yeh mantra aatma-shuddhi ka marg hai. Sant Tukaram aur Dnyaneshwar ne iska mahima gaya hai.',
      source: 'Warkari Sampraday, Maharashtra Sant Parampara',
    },
    bestTime: 'Koi bhi samay, morning walk',
    recommendedFor: 'Aatma-shuddhi, Bhakti, Chittashuddhi',
  },
  {
    id: 'hare-krishna',
    displayName: 'हरे कृष्ण',
    originalScript:
      'हरे कृष्ण हरे कृष्ण कृष्ण कृष्ण हरे हरे | हरे राम हरे राम राम राम हरे हरे',
    language: 'hi-IN',
    normalizedForms: [
      'हरे कृष्ण',
      'hare krishna',
      'hare rama hare krishna',
      'hare ram hare krishna',
    ],
    aliases: [
      'hare krishna hare krishna',
      'krishna krishna hare hare',
      'maha mantra',
    ],
    minimumSimilarity: 0.68,
    duplicateWindowMs: 3000,
    description: 'The Hare Krishna Maha Mantra',
    deity: 'Vishnu',
    meaning: {
      shortMeaning: '"Hare" = Hari (Vishnu), Krishna, Ram — Bhagwan ke teeno naam ka mahaan mantra',
      fullMeaning: 'Kali yug ka vishesh taraka mantra. Brahmanda Purana mein kaha gaya — "Hare Krishna" naam se sare paap nasht hote hain.',
      mahatmya: 'Chaitanya Mahaprabhu ne kaha — yeh mantra kali yug mein sarvadhik phaldata hai. ISKCON sangha isko poori duniya mein phailata hai.',
      source: 'Kali Santarana Upanishad, Brahmanda Purana',
    },
    bestTime: 'Brahma Muhurta, Ekadashi',
    recommendedFor: 'Prem, Bhakti, Sarva Mangal',
  },
];

/**
 * Find a preset mantra by ID
 */
export function findPresetMantra(id: string): MantraConfig | undefined {
  return PRESET_MANTRAS.find((m) => m.id === id);
}

/**
 * Deity emoji map for display
 */
export const DEITY_SYMBOLS: Record<string, string> = {
  ram: '🙏',
  krishna: '🦚',
  radha: '🌸',
  shiv: '🕉️',
  hanuman: '🪬',
  ganesh: '🐘',
  durga: '⚔️',
  sita: '🌺',
  lakshmi: '🪷',
  narayan: '🔱',
  'om-namah-shivaya': '🕉️',
  'shri-ram-jai-ram': '🙏',
  'hare-krishna': '🦚',
};
